const OPEN_DROPDOWN_MENU = 'OPEN_DROPDOWN_MENU';
const OPEN_MEGA_MENU = 'OPEN_MEGA_MENU';
const OPEN_MENU_MOBILE = 'OPEN_MENU_MOBILE';

export default {
    OPEN_DROPDOWN_MENU,
    OPEN_MEGA_MENU,
    OPEN_MENU_MOBILE
};
