const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
const FETCH_BRANCHES = 'FETCH_BRANCHES';

export default {
    FETCH_PRODUCTS,
    FETCH_CATEGORIES,
    FETCH_BRANCHES
};
