
const ADMIN_USER_UPDATE_FORM = "ADMIN_USER_UPDATE_FORM";
const ADMIN_USER_FETCH_USERS = "ADMIN_USER_FETCH_USERS";
const ADMIN_UPDATE_FILTER = "ADMIN_UPDATE_FILTER"

export default {
    ADMIN_USER_UPDATE_FORM,
    ADMIN_USER_FETCH_USERS,
    ADMIN_UPDATE_FILTER,
};
