
const ADMIN_UPDATE_FILTER = "ADMIN_UPDATE_FILTER"
const ADMIN_USER_UPDATE_FORM = "ADMIN_USER_UPDATE_FORM";
const ADMIN_USER_FETCH_USERS = "ADMIN_USER_FETCH_USERS";
const ADMIN_PRODUCT_UPDATE_FORM = "ADMIN_PRODUCT_UPDATE_FORM";
const ADMIN_PRODUCT_FETCH_PRODUCTS = "ADMIN_PRODUCT_FETCH_PRODUCTS";

export default {
    ADMIN_UPDATE_FILTER,
    ADMIN_USER_UPDATE_FORM,
    ADMIN_USER_FETCH_USERS,
    ADMIN_PRODUCT_UPDATE_FORM,
    ADMIN_PRODUCT_FETCH_PRODUCTS
};
