const TOGGLE_CART = 'TOGGLE CART';
const CHANGE_PAGE_INFO = "CHANGE PAGE INFO";
const UPDATE_CART_PRODUCTS = "UPDATE PRODUCT IN CART"

export default {
    TOGGLE_CART,
    CHANGE_PAGE_INFO,
    UPDATE_CART_PRODUCTS
};
