const TOGGLE_CART = 'TOGGLE CART';
const CHANGE_PAGE_INFO = "CHANGE PAGE INFO";
const UPDATE_CART_PRODUCTS = "UPDATE PRODUCT IN CART";
const UPDATE_AUTH_STATUS = "UPDATE_AUTH_STATUS";
const REFRESH_CART = "REFRESH_CART";

export default {
    TOGGLE_CART,
    CHANGE_PAGE_INFO,
    UPDATE_CART_PRODUCTS,
    UPDATE_AUTH_STATUS,
    REFRESH_CART
};
